### ISSUE TITLE
Game crashes at title screen

### ISSUE THREAD

**Issue by Scanode** [mizztgc/infinitas-for-linux#4]
First of all I want to thank you for this script, its been incredibly useful and helped me pick up on some holes in my own attempts to setup this game.

I was able to run it successfully, and its output didnt report any issues or errors and seemed to install fine. Was able to launch the initial client download/update tool as well. Was also able to launch the game, and got a clean sound output once I set the audio mode to single channel 44100khz in pipewire. However, once the game tried to load the title screen it crashed.

FWIW, im using a plain arch system with proprietary nvidia drivers and KDE, and the latest Wine build from my package manager,  same for the other dependencies. 

I noticed when playing in the game clients settings/menu that the fonts weren't being loaded correctly, as if the wine prefix doesnt have a proper locale set or CJK fonts installed. Could this be the potential cause of my issue? 

Thanks so much again!

**Comment by mizztgc** [comment]
I can't seem to replicate this. I think this issue stems from your PipeWire config. Both my main systems running Arch Linux + KDE + latest Wine can get to the title screen with no issues whatsoever.

Also, the fonts in the settings menu not loading correctly is because the Wineprefix doesn't have any CJK fonts installed to it. This does not contribute to your main issue in any way.

**Comment by Scanode** [comment]
Hmm, thats strange then. I fixed the font problem with winetricks. This was a fresh system too (that i had lazily setup with the archinstall script). 

Is there something in particular that needs to be done with Pipewire that the script doesn't do? I'm only using the command `pw-metadata -n settings 0 clock.force-rate 44100` which doesnt persist through restarts. The crashing happens with/without this setting enabled. Besides that its a standard install of pipewire done from pacman.

I dont think its the audio, because the game is initializing its sound and playing the Konami/Bemani/etc title screens with audio before the game crashes. On my own previous attempts, the game would not boot at all indicating audio device initilization failure (on WASAPI shared mode). 

What hardware are your Arch systems using, and how are you setting up the graphics drivers? Just curious.

**Comment by Scanode** [comment]
![image](https://github.com/user-attachments/assets/2c45fb00-a173-493d-a2d4-95c3fe9c76ba)

Ran your scripts on my primary Arch desktop instead of my BemaniPC, and it's working now. This system uses an AMD 6750 XT instead of a RTX 3060, so I must've messed something up with graphics drivers.

**Comment by mizztgc** [comment]
Alright, good to see that you got it working on your main PC. If only the e-amusement servers weren't down right now, I'd be testing with the GTX 1660 Ti I have lying around to see if I can actually replicate your initial issue.

And to answer your previous question, my main PC has an RX 6750 XT (Mesa & vulkan-radeon, version 24.1.6) and my laptop has a GeForce RTX 3050 Ti (proprietary driver, version 555.58.02).

Also, check to see if you have `nvidia-utils` and `lib32-nvidia-utils` installed on your Bemani PC. That _could_ be the reason why.
